//! Emit Rama surface AST as readable Clojure source.
//!
//! This is deliberately a source-to-source lowering: `.rama` files become
//! Clojure forms that a future macro layer can interpret. No JVM bytecode is
//! generated here.

use crate::ast::*;

/// Lower a parsed `.rama` source file to Clojure source text.
pub fn emit_clojure(file: &SourceFile) -> String {
    let mut out = String::new();
    out.push_str(";; Generated by rama-syntax-rs. Edit the .rama source instead.\n");
    out.push_str(";; Surface mapping:\n");
    out.push_str(";; - ramaop name>(...) => (deframaop name> [...])\n");
    out.push_str(";; - ramafn %name(...) => (deframafn %name [...])\n");
    out.push_str(";; - $$p --> path > *x => (local-select> path $$p :> *x)\n");
    out.push_str(
        ";; - $$p !<-- path, termval(...) => (local-transform> [path (termval ...)] $$p)\n",
    );
    out.push_str(";; - if (...) { ... } else { ... } => (<<if ... ... (else>) ...)\n\n");

    for (idx, item) in file.items.iter().enumerate() {
        if idx > 0 {
            out.push('\n');
        }
        out.push_str(&emit_item(item, 0));
        out.push('\n');
    }

    out
}

fn emit_item(item: &Item, indent: usize) -> String {
    match item {
        Item::RamaOp(op) => emit_ramaop(op, indent),
        Item::RamaFn(func) => emit_ramafn(func, indent),
        Item::PState(decl) => emit_pstate(decl, indent),
    }
}

fn emit_ramaop(op: &RamaOpDef, indent: usize) -> String {
    let pad = spaces(indent);
    let params = op
        .params
        .iter()
        .map(|p| emit_param(&p.node))
        .collect::<Vec<_>>()
        .join(" ");
    let body = emit_block(&op.body, indent + 2);
    format!(
        "{pad}(deframaop {} [{}]\n{}\n{pad})",
        op.name.node, params, body
    )
}

fn emit_ramafn(func: &RamaFnDef, indent: usize) -> String {
    let pad = spaces(indent);
    let params = func
        .params
        .iter()
        .map(|p| emit_param(&p.node))
        .collect::<Vec<_>>()
        .join(" ");
    let body = if func.body.is_empty() {
        format!("{}nil", spaces(indent + 2))
    } else {
        func.body
            .iter()
            .map(|binding| emit_inline_binding(binding, indent + 2))
            .collect::<Vec<_>>()
            .join("\n")
    };
    format!(
        "{pad}(deframafn {} [{}]\n{}\n{pad})",
        func.name.node, params, body
    )
}

fn emit_pstate(decl: &PStateDecl, indent: usize) -> String {
    let pad = spaces(indent);
    let key = emit_type(&decl.key.node);
    let value = emit_pstate_value_schema(&key, &decl.value.node, indent + 3);
    format!(
        "{pad}(declare-pstate s $${}\n{}{})",
        decl.name.node,
        spaces(indent + 2),
        value
    )
}

fn emit_pstate_value_schema(key: &str, value: &TypeExpr, indent: usize) -> String {
    match value {
        TypeExpr::Fixed { fields } => {
            let field_pad = spaces(indent + 3);
            let mut out = format!("{{{key}\n{}(fixed-keys-schema", spaces(indent + 1));
            if fields.is_empty() {
                out.push_str(" {})}");
                return out;
            }
            out.push('\n');
            out.push_str(&field_pad);
            out.push('{');
            for (idx, (name, ty)) in fields.iter().enumerate() {
                if idx > 0 {
                    out.push('\n');
                    out.push_str(&field_pad);
                    out.push(' ');
                }
                out.push_str(&format!("{} {}", emit_string(name), emit_type(ty)));
            }
            out.push_str(")})");
            out
        }
        TypeExpr::Map { value } => {
            format!(
                "{{{key} (map-schema {key} {} {{:subindex? true}})}}",
                emit_type(value)
            )
        }
        _ => format!("{{{key} {}}}", emit_type(value)),
    }
}

fn emit_type(ty: &TypeExpr) -> String {
    match ty {
        TypeExpr::Named(name) => name.clone(),
        TypeExpr::Fixed { fields } => {
            let fields = fields
                .iter()
                .map(|(name, ty)| format!("{} {}", emit_string(name), emit_type(ty)))
                .collect::<Vec<_>>()
                .join(" ");
            format!("(fixed-keys-schema {{{fields}}})")
        }
        TypeExpr::Map { value } => format!("(map-schema Object {})", emit_type(value)),
        TypeExpr::Object => "Object".to_string(),
    }
}

fn emit_block(block: &Block, indent: usize) -> String {
    if block.stmts.is_empty() {
        return format!("{}nil", spaces(indent));
    }
    block
        .stmts
        .iter()
        .map(|stmt| emit_stmt(stmt, indent))
        .collect::<Vec<_>>()
        .join("\n")
}

fn emit_stmt(stmt: &Stmt, indent: usize) -> String {
    let pad = spaces(indent);
    match stmt {
        Stmt::Anchor { anchor, .. } => format!("{pad}(anchor> <{}>)", anchor.node),
        Stmt::Effect { value, binding, .. } => emit_effect_stmt(value, binding.as_ref(), indent),
        Stmt::Transform { pstate, path, .. } => emit_transform_stmt(pstate, path, indent),
        Stmt::Select {
            pstate,
            path,
            target,
            ..
        } => emit_select_stmt(pstate, path, target.as_ref(), indent),
        Stmt::HookNamed { name, arg, .. } => {
            let mut parts = vec!["hook>".to_string(), name.node.clone()];
            if let Some(arg) = arg {
                parts.push(emit_expr(arg));
            }
            format!("{pad}({})", parts.join(" "))
        }
        Stmt::HookAnchor { anchor, .. } => format!("{pad}(hook> <{}>)", anchor.node),
        Stmt::Unify { anchors, .. } => {
            let anchors = anchors
                .iter()
                .map(|a| format!("<{}>", a.node))
                .collect::<Vec<_>>()
                .join(" ");
            format!("{pad}(unify> {anchors})")
        }
        Stmt::If {
            condition,
            consequence,
            alternative,
            ..
        } => emit_if_stmt(condition, consequence, alternative.as_ref(), indent),
        Stmt::Atomic { body, .. } => {
            let body = emit_block(body, indent + 2);
            format!("{pad}(<<atomic\n{body}\n{pad})")
        }
        Stmt::Sink { target, .. } => format!("{pad}(:> {})", emit_binding_target(target)),
        Stmt::RamaFn(func) => emit_ramafn(func, indent),
    }
}

fn emit_effect_stmt(value: &Expr, binding: Option<&EffectBinding>, indent: usize) -> String {
    let pad = spaces(indent);
    let Some(binding) = binding else {
        return format!("{pad}{}", emit_expr(value));
    };

    let target = emit_binding_target(&binding.target);
    let effect = emit_expr_with_binding(value, &target);
    if let Some(alias) = &binding.alias {
        format!(
            "{pad}(do\n{}{}\n{}(alias> {}))",
            spaces(indent + 2),
            effect,
            spaces(indent + 2),
            alias.node
        )
    } else {
        format!("{pad}{effect}")
    }
}

fn emit_transform_stmt(
    pstate: &crate::span::Spanned<String>,
    path: &[Expr],
    indent: usize,
) -> String {
    let pad = spaces(indent);
    let pstate = format!("$${}", pstate.node);
    let joined_path = path.iter().map(emit_expr).collect::<Vec<_>>().join(" ");
    let one_line = format!("{pad}(local-transform> [{joined_path}] {pstate})");
    if one_line.len() <= 100 {
        return one_line;
    }

    let path_pad = spaces(indent + 2);
    let path_cont_pad = spaces(indent + 3);
    let mut out = format!("{pad}(local-transform>\n{path_pad}[");
    for (idx, segment) in path.iter().enumerate() {
        if idx > 0 {
            out.push('\n');
            out.push_str(&path_cont_pad);
        }
        out.push_str(&emit_expr(segment));
    }
    out.push_str(&format!("]\n{path_pad}{pstate}\n{pad})"));
    out
}

fn emit_select_stmt(
    pstate: &crate::span::Spanned<String>,
    path: &[Expr],
    target: Option<&BindingTarget>,
    indent: usize,
) -> String {
    let pad = spaces(indent);
    let pstate = format!("$${}", pstate.node);
    let path = emit_select_path(path);
    match target {
        Some(target) => format!(
            "{pad}(local-select> {path} {pstate} :> {})",
            emit_binding_target(target)
        ),
        None => format!("{pad}(local-select> {path} {pstate})"),
    }
}

fn emit_select_path(path: &[Expr]) -> String {
    match path {
        [one] => emit_expr(one),
        _ => format!(
            "[{}]",
            path.iter().map(emit_expr).collect::<Vec<_>>().join(" ")
        ),
    }
}

fn emit_if_stmt(
    condition: &Expr,
    consequence: &Block,
    alternative: Option<&Block>,
    indent: usize,
) -> String {
    let pad = spaces(indent);
    let consequence = emit_block(consequence, indent + 2);
    match alternative {
        Some(alternative) => {
            let alternative = emit_block(alternative, indent + 2);
            format!(
                "{pad}(<<if {}\n{}\n{}(else>)\n{}\n{pad})",
                emit_expr(condition),
                consequence,
                spaces(indent + 1),
                alternative
            )
        }
        None => format!(
            "{pad}(<<if {}\n{}\n{pad})",
            emit_expr(condition),
            consequence
        ),
    }
}

fn emit_inline_binding(binding: &InlineBinding, indent: usize) -> String {
    let pad = spaces(indent);
    match (&binding.value, &binding.target) {
        (Some(value), InlineTarget::Binding(target)) => {
            format!(
                "{pad}{}",
                emit_expr_with_binding(value, &emit_binding_target(target))
            )
        }
        (None, InlineTarget::Binding(target)) => {
            format!("{pad}(:> {})", emit_binding_target(target))
        }
        (Some(value), InlineTarget::Call(call)) => {
            let args = std::iter::once(emit_expr(value))
                .chain(call.args.iter().map(emit_expr))
                .collect::<Vec<_>>()
                .join(" ");
            format!("{pad}({} {args})", call.callee.node)
        }
        (None, InlineTarget::Call(call)) => format!("{pad}{}", emit_call(call)),
    }
}

fn emit_expr_with_binding(value: &Expr, target: &str) -> String {
    match value {
        Expr::Call(call) => emit_call_with_tail(call, Some(format!(":> {target}"))),
        _ => format!("(identity {} :> {target})", emit_expr(value)),
    }
}

fn emit_expr(expr: &Expr) -> String {
    match expr {
        Expr::Call(call) => emit_call(call),
        Expr::List { elems, .. } => format!(
            "[{}]",
            elems.iter().map(emit_expr).collect::<Vec<_>>().join(" ")
        ),
        Expr::Map { entries, .. } => emit_map(entries),
        Expr::String(s) => emit_string(&s.node),
        Expr::Anchor(a) => format!("<{}>", a.node),
        Expr::Keyword(k) => format!(":{}", k.node),
        Expr::Binding(b) => b.node.clone(),
        Expr::PState(p) => format!("$${}", p.node),
        Expr::Pipe(p) => format!("|{}", p.node),
        Expr::Ident(i) => i.node.clone(),
        Expr::Int(i) => i.node.to_string(),
        Expr::Bool(b) => b.node.to_string(),
    }
}

fn emit_call(call: &CallExpr) -> String {
    emit_call_with_tail(call, None)
}

fn emit_call_with_tail(call: &CallExpr, tail: Option<String>) -> String {
    let mut parts = Vec::with_capacity(call.args.len() + 2);
    parts.push(call.callee.node.clone());
    parts.extend(call.args.iter().map(emit_expr));
    if let Some(tail) = tail {
        parts.push(tail);
    }
    format!("({})", parts.join(" "))
}

fn emit_map(entries: &[MapEntry]) -> String {
    if entries.is_empty() {
        return "{}".to_string();
    }
    let mut parts = Vec::with_capacity(entries.len() * 2);
    for entry in entries {
        let key = emit_expr(&entry.key);
        parts.push(key.clone());
        parts.push(entry.value.as_ref().map(emit_expr).unwrap_or(key));
    }
    format!("{{{}}}", parts.join(" "))
}

fn emit_binding_target(target: &BindingTarget) -> String {
    match target {
        BindingTarget::Name(name) => name.node.clone(),
        BindingTarget::Map(entries) => emit_map(entries),
        BindingTarget::List(elems) => format!(
            "[{}]",
            elems.iter().map(emit_expr).collect::<Vec<_>>().join(" ")
        ),
    }
}

fn emit_param(param: &Param) -> String {
    match param {
        Param::Binding(name) | Param::Ident(name) => name.clone(),
    }
}

fn emit_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out.push('"');
    out
}

fn spaces(n: usize) -> String {
    " ".repeat(n)
}
